### ISSUE TITLE
Create regular meeting

### ISSUE THREAD

**Issue by lukekarrys** [openjs-foundation/package-metadata-interoperability-collab-space#1]
Now that we have a Collab Space, we should create a regular meeting to discuss ongoing work.

What do folks think about cadence and when to start?

**Comment by Ethan-Arrowood** [comment]
IMO we should start with once a month. I think we can also reasonably use CPC Working Sessions to collaborate on work. Otherwise we could try to do async check in's once a month. We really only have one active workstream (package json research), and then the next workstream would be @wesleytodd pkg stuff.

**Comment by Ethan-Arrowood** [comment]
I took a look at the OpenJS Foundation calendar. Here are some options for us:

- (Vote: 🚀) First Tuesday of Every Month at 4pm ET (0 conflicts with any other event across Node.js Project Calendar, OpenJS Foundation Calendar, and WinterCG Meeting Calendar)
- (Vote: ❤️) First Tuesday of Every Month at 3pm ET (only conflicts with the Tuesday Package Maintenance Team meetings)

Since most of the folks on Node.js Package Maintenance Team meeting are also apart of this Collab space I'm in favor of the earlier 3pm ET slot assuming we can official modify the Package Maintenance Team meeting schedule. Furthermore, I recently proposed that the Package Maintenance Team move to a once-a-month cadence as well since we've had the same non-changing agenda for _months_ (_years?_) now. 

I don't think any earlier times would work since those slots are used up by the very active CPC and Standards calls. Similarly, I prefer the Tuesday day because it tends to be a high-volume meeting day for many folks (it surely is for me due to CPC and Standards calls 😉). I've always preferred to load up meetings onto a single day, earlier in the week, than anything else.

Use emojis to vote. Reply/comment with any other suggestions or comments regrading the two times I've selected. 

Lets get this scheduled by the first week of October so we can have our first meeting then!

**Comment by Ethan-Arrowood** [comment]
@bensternthal can you help me get this on the calendar for next week? Thanks!

**Comment by bensternthal** [comment]
@Ethan-Arrowood Sure!

Note I'll be using the LFX meeting tool, this just means folks will either login with their LFX ID or join as guests (its very straightforward).

One thing to confirm:

- Would you want this meeting to be recorded?

**Comment by Ethan-Arrowood** [comment]
Yes please :)

**Comment by bensternthal** [comment]
Ok scheduled and I added you to the invite.

Note I also copied this meeting to the public calendar.

Do let me know if you need any adjustments and of course reach out if you run into any problems with the actual meeting.

**Comment by ljharb** [comment]
oof, do we really have to start using lfx for meetings? it’s so much less convenient to log in

**Comment by bensternthal** [comment]
Yep we do need to start using it.

Note you don't have to log in you can also just join as a guest.

**Comment by ljharb** [comment]
If i can’t just click a zoom link and make it in, then i might as well log in, it’s just about as inconvenient.

**Comment by wesleytodd** [comment]
This is new to me, I assume the calendar invite will include instructions?

**Comment by bensternthal** [comment]
@Ethan-Arrowood do you have a list of folks you want to have invited/added to the invite? Or is it enough to have it on the public calendar? 

Happy to add folks if you can provide me with their emails, just send to me via slack.

**Comment by Ethan-Arrowood** [comment]
No one in particular. I hope the right people have notifications on for this thread. Otherwise, I'll cross post to Slack. I don't really have anyones emails anyways. Just GitHub usernames if anything.
